apiVersion: batch/v1
kind: CronJob
metadata:
  name: demo-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cronjob
            image: job-cronjob-demo:latest
            imagePullPolicy: IfNotPresent
            args: ["cronjob"]
          restartPolicy: Never

