apiVersion: batch/v1
kind: Job
metadata:
  name: demo-job
spec:
  template:
    spec:
      containers:
      - name: job
        image: job-cronjob-demo:latest
        imagePullPolicy: IfNotPresent
        args: ["job"]
      restartPolicy: Never
  backoffLimit: 2

