apiVersion: apps/v1
kind: Deployment
metadata:
  name: rbac-demo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rbac-demo
  template:
    metadata:
      labels:
        app: rbac-demo
    spec:
      containers:
      - name: rbac-demo-container
        image: rbac-demo:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000 